# Generated by Django 4.0 on 2021-12-21 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзина'},
        ),
        migrations.AddField(
            model_name='album',
            name='out_of_stock',
            field=models.IntegerField(default=False, verbose_name='Нет в наличии'),
        ),
    ]
