# Generated by Django 4.0 on 2021-12-21 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicshop', '0002_alter_cart_options_album_out_of_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='out_of_stock',
            field=models.BooleanField(default=False, verbose_name='Нет в наличии'),
        ),
    ]
