# Generated by Django 4.0 on 2021-12-25 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicshop', '0004_remove_cart_for_anonymous_user_cart_session_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='musicshop.customer', verbose_name='Покупатель'),
        ),
    ]
